# Generated by Django 2.2.3 on 2019-07-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190721_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Colors',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Short_intro',
            new_name='short_intro',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sizes',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Strike_price',
            new_name='strike_price',
        ),
    ]
